version: "3.9"

services:
  rust-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GIT_HASH: ${GIT_HASH:-development}
    container_name: rust_service
    expose:
      - "8080"
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=${MONGO_URI}
      - RUST_LOG=${RUST_LOG}
      - IMAGE_RECOGNITION_URL=${IMAGE_RECOGNITION_URL}
    restart: unless-stopped

  python-api:
    build:
      context: ./image_recognition
      dockerfile: Dockerfile
      args:
        GIT_HASH: ${GIT_HASH:-development}
    container_name: python_api
    ports:
      - "8081:8080"
    networks:
      - app_network
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - rust-service  
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
